### ISSUE TITLE
remove "in" and "out" from "system" nodes

### ISSUE THREAD

**Issue by x37v** [Cycling74/rnbo-runner-panel#80]
those aren't actually in the jack client name so they add confusion if you're trying to create/destroy connections

**Comment by fde31** [comment]
Fine by me but for clarification - where exactly are they causing confusing? If u map from UI to OSC cli? I assume u'd just want to have the display diff?

**Comment by x37v** [comment]
if i ssh in i can manage connections with `jack_connect` and the name "system-in" doesn't match what I can use on the commandline.
also, it doesn't match the names we have in the OSCquery json, for instance `/rnbo/jack/info/ports/audio/sinks`

**Comment by fde31** [comment]
sure, we can just remove the display label. Internally `in` and `out` are basically used to distinguish between the two nodes in the graphs as I suspect u'd not expect the system I/O to be a single node.

Based on that I generally think trying to 1:1 map the UI / UX to whatever jack does is a bit of a rabbit-hole and potentially not the most obvious and effectively tailors for the dev experience (with jack knowledge) rather than the user.

Again, we can remove the display label here but I'd like us to be a bit more vary that this isn't jack and that that folks preferring the raw JSON state tree and Jack might just be pointed to that rather than expecting to have all things match 100% for an improved of the actual UI.
