### ISSUE TITLE
new instances get offset weirdly after being placed on graph

### ISSUE THREAD

**Issue by x37v** [Cycling74/rnbo-runner-panel#86]
https://github.com/Cycling74/rnbo-runner-panel/assets/65796/a4702690-3ab1-4317-9aeb-ea5f32a3ffb7

**Comment by fde31** [comment]
OK. I made a PR for that - this happened due to a timing issue. Whenever the overall connections change we compare the list of nodes against the existing system, control and patcher nodes. The connections change is sent out prior to the patcher instance node being created so it was flagged as a "control" node.

The fix I added is not pretty and has potentially some edge cases might break it but this check if the unknown node name begins with any of the patcher names assuming that the runner will always use `<patcher_name>-<number>` as the scheme.
